---

- name: make maxscale directory
  file:
    path: /opt/project/maxscale
    state: directory

- name: maxscale config file
  template:
    src: maxscale.cnf.j2
    dest: /opt/project/maxscale/maxscale.cnf

