---

- name: docker compose config file 
  template:
    src: docker-compose.yml.j2
    dest: /opt/project/docker-compose.yml
    mode: "0644"

- name: run docker compose file
  community.general.docker_compose:
    project_src: /opt/project/
    files:
      - docker-compose.yml
    state: present

