---
- name: Install aptitude
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install required system package
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: add docker GPG apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: update apt and install docker-ce
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-compose-plugin
    - containerd.io

- name: install docker module for python
  become: true
  pip:
    name: "{{ item }}"
  loop:
    - docker==6.1.3
    - docker-compose

# - name: get docker shell for download
#   get_url:
#     url: https://get.docker.com
#     dest: /tmp/get-docker.sh
#     mode: '0755'
  
# - name: Execute Docker installation script
#   shell: sh /tmp/get-docker.sh

- name: pull images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - mariadb:10.3
    - mariadb/maxscale:6.3.1
    - redis:7.0